# Generated by Django 6.0.1 on 2026-01-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_city_order_full_name_order_phone_and_more'),
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy_now_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='buy_now_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
