# Generated by Django 6.0.1 on 2026-01-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_buy_now_product_order_buy_now_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('PLACED', 'Placed')], default='Processing', max_length=10),
        ),
    ]
