# Generated by Django 6.0.1 on 2026-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('PLACED', 'Placed')], default='PLACED', max_length=10),
        ),
    ]
